# Generated by Django 5.0 on 2023-12-27 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
