# Generated by Django 5.0 on 2023-12-30 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_classes_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
