# Generated by Django 5.0 on 2023-12-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classes_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='time_slot',
            field=models.CharField(choices=[('11:00-11:50', '11:00-11:50'), ('12:00-12:50', '12:00-12:50'), ('13:00-13:50', '13:00-13:50'), ('14:00-14:50', '14:00-14:50'), ('15:00-15:50', '15:00-15:50'), ('16:00-16:50', '16:00-16:50'), ('17:00-17:50', '17:00-17:50'), ('18:00-18:50', '18:00-18:50')], max_length=20),
        ),
    ]
