# Generated by Django 5.0 on 2024-01-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_enrollments_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollments',
        ),
    ]
