# Generated by Django 5.0 on 2024-01-16 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_alter_enrollments_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 16, 9, 59, 9, 992573, tzinfo=datetime.timezone.utc)),
        ),
    ]
