# Generated by Django 5.0 on 2024-01-25 09:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_alter_classes_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 9, 7, 7, 784557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='enrollments',
            name='class_enrolled',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
    ]
