# Generated by Django 5.0 on 2024-01-25 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_alter_classes_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 25, 15, 36, 37, 72755, tzinfo=datetime.timezone.utc)),
        ),
    ]
