# Generated by Django 5.0 on 2024-01-28 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0017_classes_is_active_alter_classes_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 1, 28, 16, 12, 34, 928496, tzinfo=datetime.timezone.utc)),
        ),
    ]
