# Generated by Django 5.0 on 2024-01-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_customuser_customusers_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='emergency_contact_num',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='phone_num',
        ),
    ]
