# Generated by Django 5.0 on 2024-01-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_customusers_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUsers',
        ),
    ]
