# Generated by Django 5.0 on 2024-01-15 06:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0010_delete_customusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('phone_num', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')], verbose_name='Phone number')),
                ('emergency_contact_name', models.CharField(max_length=50, null=True)),
                ('emergency_contact_num', models.CharField(max_length=8, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must contain only digits.', regex='^[0-9]+$')], verbose_name='Emergency contact number')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
